export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  CIRCUIT_OVERLOADED: "CIRCUIT_OVERLOADED",
  CIRCUIT_IN_MAINTENANCE: "CIRCUIT_IN_MAINTENANCE",
  PHASE_IMBALANCE: "PHASE_IMBALANCE",
  NO_USABLE_PLAN: "NO_USABLE_PLAN"
} as const;
