export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  CIRCUIT_OVERLOADED: "CIRCUIT_OVERLOADED",
  CIRCUIT_UNDER_MAINTENANCE: "CIRCUIT_UNDER_MAINTENANCE",
  PHASE_IMBALANCE_EXCEEDED: "PHASE_IMBALANCE_EXCEEDED",
  NO_USABLE_PLAN: "NO_USABLE_PLAN"
} as const;
